title: lifeblood
description: hyperfocused Jekyll theme for documentation
encoding: utf-8

sass:
  style: compressed

exclude:
  - README.md
  - LICENSE
  - Gemfile.lock

footer: "(c) 2021 <a href='https://sporeball.dev' target='_blank'>sporeball</a>"
