title: lifeblood
description: hyperfocused Jekyll theme for documentation
encoding: utf-8

sass:
  style: compressed

exclude:
  - README.md
  - LICENSE
  - Gemfile.lock

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

footer_left: "made with <span class='love'>&lt;3</span> by <a href='https://sporeball.dev' target='_blank'>sporeball</a>"
footer_right: "&copy; 2021"
