title: lifeblood
description: a hyperfocused Jekyll theme for documentation
encoding: utf-8

sass:
  style: compressed

exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# home: ""
# nav_categories: []

theme_color: "#fc88fc"

footer_left: "made with <span class='love'>&lt;3</span> by <a href='https://sporeball.dev' target='_blank'>sporeball</a>"
footer_right: "&copy; 2022"

# enable_custom: true
# fonts: []

enable_dark_theme: true
# enable_versions: true
